name: demixing
channels:
  - defaults
  - pytorch
  - nvidia

dependencies:
  - python=3.9    
  - pip
  - numpy
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.7
  - pip:
    - pytorch-lightning[extra]==1.9.4
    - torch-optimizer
    - musdb
    - julius
    - demucs
    - git+https://github.com/yoyololicon/norbert
    - pedalboard
    - audio-data-pytorch
    - pyloudnorm
    - torch_fftconv
    - streamlit 
    - librosa
    - soundfile
